### ISSUE TITLE
Unable to access portainer with http

### ISSUE THREAD

**Issue by MrHappy** [SavageSoftware/portainer-backup#13]
I've ports 8000:8000 and 9443:9443 for portainer.
I can access port 9443 to manage portainer fine, with port 8000 I get 'not found'.
This is the default install of portainer (as far as I can tell).
What did I miss/do wrong?

**Comment by Marty56** [comment]
please provide your success story. I have the same problem.

**Comment by crispybegs** [comment]
did you fix this? same problem here

**Comment by yppdr** [comment]
Hello ! 

Add **NODE_TLS_REJECT_UNAUTHORIZED: 0** in your compose file and Voila!

You will get a warning in the console but nothing serious.
