### ISSUE TITLE
{{DATE}} not updating the folder path using scheduled run

### ISSUE THREAD

**Issue by oliroe** [SavageSoftware/portainer-backup#4]
Hi

First of all, awesome tool

I'm having an issue with the folder path not updating when running on a schedule. Below is a screenshot of my docker compose with {{DATE}} in the path and also the log showing the incorrect folder being used for the backup

![image](https://user-images.githubusercontent.com/4500141/176999597-a21509d4-b356-4517-a43f-056f5be36076.png)

![image](https://user-images.githubusercontent.com/4500141/176999670-c5e799c2-5793-4450-9010-9a12fbf5cc39.png)

Thanks

Edit..everything works ok when using the backup command rather than schedule

![image](https://user-images.githubusercontent.com/4500141/176999885-3cfdcc7d-cbd1-43c8-b6d8-eab4459ecaa1.png)

**Comment by oliroe** [comment]
The new directory is created when first run but every subsequent run uses that same folder. As a workaround I've created a cronjob to run this with command 'backup' rather than 'schedule'

**Comment by savageautomate** [comment]
Definitely sounds like a bug.  It should be an easy fix.  I should have time to look into it in the next week or so.  Please bump this thread for an update if you don't hear back in a couple of weeks.  Thanks, Robert

**Comment by oliroe** [comment]
Sorry to bug you, just a bump as suggested above
:)

**Comment by savageautomate** [comment]
@oliroe 

No bother at all.  I have made the changes and published as version 0.0.7.  Let me know if this fixes it for you! 

Thanks, Robert

**Comment by oliroe** [comment]
Just finished testing and it's creating folders as expected

Really appreciate you fixing this

**Comment by savageautomate** [comment]
@oliroe 

Glad to hear its working!  Thank you for confirming!
